### ISSUE TITLE
Hello, Compilation failed after changing Kafka version 0.10.0.0

### ISSUE THREAD

**Issue by iduanyingjie** [dibbhatt/kafka-spark-consumer#54]
0.10.0.0 version of KafkaConsumer does not have the methods of beginningOffsets and endOffsets,
KafkaUtils uses these two methods.

**Comment by dibbhatt** [comment]
Yes, Kafka is having issues with backward compatibility of their API. In that case you can use the earlier version of the Consumer 1.0.13 . That will work with Kafka 0.10

You can get it from here : https://github.com/dibbhatt/kafka-spark-consumer/tree/2688a2e6da4cdd659c18e16ff22af0efad7bc185

**Comment by dibbhatt** [comment]
I can Kafka 0.10.1 has beginningOffsets and endOffsets

**Comment by dibbhatt** [comment]
Hi @iduanyingjie .Did you able to solve the issue with Kafka 0.10.1 ? Let me know if you need any help from me .

**Comment by dibbhatt** [comment]
hi @iduanyingjie closing this issue. let me me know if you need any further help.

**Comment by dibbhatt** [comment]
hi @iduanyingjie , if you do not mind, can you tell me name of your organization also if this consumer if running in production in your organization.
