### ISSUE TITLE
error: object ProcessedOffsetManager is not a member of package consumer.kafka

### ISSUE THREAD

**Issue by Srinivasan-pp** [dibbhatt/kafka-spark-consumer#45]
Hi,

I tried to use 1.0.6 version jar, and try to execute via spark, it is throwing me error:
error: object ProcessedOffsetManager is not a member of package consumer.kafka

the command i executed: scala> import consumer.kafka.ProcessedOffsetManager;

**Comment by dibbhatt** [comment]
Hi @Srinivasan-pp You can git clone the repo and build it with Spark 1.6. You may need to do some minor changes to make it work with Spark 1.6. Its very easy to do. Do let me know if you need any help. 

Or you can use V 1.0.9 which will work with Spark 1.0.6
